# RUN:    docker compose -f docker-compose-dev.yml up -d
# BUILD:  docker build -t nguyenminh1301/per:<tagname> .
# PUSH:   docker push nguyenminh1301/per:<tagname>

services:
  app:
    container_name: per
    # Build from local
    build:
      context: .
      dockerfile: Dockerfile
    image: per-dev
    restart: unless-stopped

    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=${SERVER_PORT}

      # --- PostgreSQL (app đọc từ env) ---
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

      # --- Redis ---
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

      # --- JWT ---
      - JWT_SECRET=${JWT_SECRET}
      - ACCESS_TOKEN_TTL=${ACCESS_TOKEN_TTL}
      - REFRESH_TOKEN_TTL=${REFRESH_TOKEN_TTL}
      - JWT_ISSUER=${JWT_ISSUER}

      # --- Cloudinary ---
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - CLOUDINARY_FOLDER=${CLOUDINARY_FOLDER}

      # --- Mail ---
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_SMTP_CONNECTION_TIMEOUT=${MAIL_SMTP_CONNECTION_TIMEOUT}
      - MAIL_SMTP_TIMEOUT=${MAIL_SMTP_TIMEOUT}
      - MAIL_SMTP_WRITETIMEOUT=${MAIL_SMTP_WRITETIMEOUT}
      - MAIL_SMTP_AUTH=${MAIL_SMTP_AUTH}
      - MAIL_SMTP_STARTTLS=${MAIL_SMTP_STARTTLS}

      # --- CORS & App URLs ---
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - APP_BASE_URL=${APP_BASE_URL}

      # --- PayOS ---
      - PAY_OS_CLIENT_ID=${PAY_OS_CLIENT_ID}
      - PAY_OS_API_KEY=${PAY_OS_API_KEY}
      - PAY_OS_CHECKSUM_KEY=${PAY_OS_CHECKSUM_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}       # đặt trong .env nếu muốn đổi
      - POSTGRES_USER=${POSTGRES_USERNAME}        # map từ .env của bạn
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports: [ "5432:5432" ]
    volumes: [ "db:/var/lib/postgresql/data" ]

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI -> http://localhost:8025

volumes:
  db:
