debug: false

spring:
  config:
    import: classpath:resilience4j/resilience4j-prod.yml

jpa:
  hibernate:
    ddl-auto: validate
  show-sql: true

security:
  jwt:
    secret: ${JWT_SECRET}
    access-ttl: ${ACCESS_TOKEN_TTL}
    refresh-ttl: ${REFRESH_TOKEN_TTL}
    issuer: ${JWT_ISSUER}

app:
  base-url: ${APP_BASE_URL}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
  elasticsearch:
    auto-reindex: ${APP_ELASTICSEARCH_AUTO_REINDEX:true}
  mail:
    from: ${MAIL_FROM}
  rag:
    auto-index: ${APP_RAG_AUTO_INDEX:true}
    chat-model: ${OPENAI_CHAT_MODEL}
    search-top-k: ${RAG_SEARCH_TOP_K}
    similarity-threshold: ${RAG_SIMILARITY_THRESHOLD}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  folder: ${CLOUDINARY_FOLDER}

payos:
  client-id: ${PAY_OS_CLIENT_ID}
  api-key: ${PAY_OS_API_KEY}
  checksum-key: ${PAY_OS_CHECKSUM_KEY}
  webhook-path: /per/payments/payos/webhook
  return-path: /payments/payos/return
  cancel-path: /payments/payos/return

payment:
  expiration-check-interval: PT1M
  expiration-check-batch-size: 50

springdoc:
  swagger-ui:
    path: /per/api-docs
    config-url: /per/v3/api-docs/swagger-config
    url: /per/v3/api-docs
  api-docs:
    path: /per/v3/api-docs
  server-url: ${APP_BASE_URL}