debug: false

jpa:
  hibernate:
    ddl-auto: validate
  show-sql: true

security:
  jwt:
    secret: ${JWT_SECRET}                   # base64 256-bit+
    access-ttl: ${ACCESS_TOKEN_TTL:PT15M}   # 15 minutes (ISO-8601)
    refresh-ttl: ${REFRESH_TOKEN_TTL:P30D}  # 30 days (ISO-8601)
    issuer: ${JWT_ISSUER:per-auth-service}

app:
  base-url: ${APP_BASE_URL}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
  mail:
    from: ${MAIL_FROM}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  folder: ${CLOUDINARY_FOLDER:per/uploads}

payos:
  client-id: ${PAY_OS_CLIENT_ID}
  api-key: ${PAY_OS_API_KEY}
  checksum-key: ${PAY_OS_CHECKSUM_KEY}
  webhook-path: /per/payments/payos/webhook
  return-path: /payments/payos/return
  cancel-path: /payments/payos/return

payment:
  expiration-check-interval: PT1M
  expiration-check-batch-size: 50

springdoc:
  swagger-ui:
    path: /per/api-docs
    config-url: /per/v3/api-docs/swagger-config
    url: /per/v3/api-docs
  api-docs:
    path: /per/v3/api-docs
  server-url: ${APP_BASE_URL}

resilience4j:
  circuitbreaker:
    instances:
      media:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        eventConsumerBufferSize: 10
        registerHealthIndicator: true

  ratelimiter:
    instances:
      # Auth
      authStrict:
        limitForPeriod: 20
        limitRefreshPeriod: 60s
        timeoutDuration: 0
        registerHealthIndicator: true
      authVeryStrict:
        limitForPeriod: 20
        limitRefreshPeriod: 1h
        timeoutDuration: 0
        registerHealthIndicator: true
      authModerate:
        limitForPeriod: 30
        limitRefreshPeriod: 60s
        timeoutDuration: 5s
        registerHealthIndicator: true

      #Media
      mediaSingle:
        limitForPeriod: 3
        limitRefreshPeriod: 5s
        timeoutDuration: 2s
        registerHealthIndicator: true
      mediaMultipart:
        limitForPeriod: 10
        limitRefreshPeriod: 20s
        timeoutDuration: 5s
        registerHealthIndicator: true
