global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "per-prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
    metrics_path: "/metrics"

  - job_name: "per-springboot"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:8080"]
    metrics_path: "/actuator/prometheus"

  - job_name: "per-node-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: [ "node-exporter:9100" ]

  - job_name: "per-redis-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: [ "redis-exporter:9121" ]
    metrics_path: "/metrics"

  - job_name: "postgres-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: [ "postgres-exporter:9187" ]
    metrics_path: "/metrics"
